fix rcS ufs913

diff --git a/tdt/cvs/cdk/root/release/rcS_stm23_neutrino_ufs913 b/tdt/cvs/cdk/root/release/rcS_stm23_neutrino_ufs913
--- a/tdt/cvs/cdk/root/release/rcS_stm23_neutrino_ufs913
+++ b/tdt/cvs/cdk/root/release/rcS_stm23_neutrino_ufs913
@@ -140,14 +140,27 @@ if [ ! -e /var/etc/.firstboot ]; then
    until false
    do
       echo "starting neutrino ->"
-      /usr/local/bin/neutrino -v 3
-      if [ -e /tmp/.reboot ]; then
-         echo "REBOOT"
-         init 6
-      else
-         echo "SHUTDOWN"
-         init 0
-      fi
+      /usr/local/bin/neutrino
+      rtv=$?
+      echo "neutrino ended <- RTV: " $rtv
+      case "$rtv" in
+		0) echo "0"
+		   echo "ERROR"
+		   init 6;;
+		1) echo "1"
+		   echo "SHUTDOWN"
+		   init 0;;
+		2) echo "2"
+		   echo "REBOOT"
+		   init 6;;
+		3) echo "3"
+		   echo "RESTART"
+		   echo "0" > /proc/progress
+		   showiframe -p /var/boot/bootlogo.mvi &;;
+		*) echo "*"
+		   echo "ERROR"
+		   init 6;;
+      esac
    done
 fi
 
